== Weirdness

According to hadolint, these are valid:

. `+ARG 9=3+` and then `RUN echo "$9"`
. `ARG s/f=3`, but then `RUN echo "${s/f}"` and `RUN echo $s/f` both fail (looking for `$s`)

The grammar does appear to be underspecified for these, might be really interesting to fuzz the grammar...

== Idea on parsing many lines

The library is pretty focused on atomic Dockerfile lines currenty; it's also agnostic as to
requirements such as "only an `ARG` instruction may precede a `FROM` ". We can make this a little
better tho:

- `consume_line` for each line, figuring out if we should escape or not (is the first lexeme a comment?)
- then just `List.map docker_of_line` for each, returning a `dockerfile` (`list(t)`) type

It's relatively cheap, and allows us to know what "logical" (not physical) line we're on for each,
without requiring much state from the parser. The downside is we have to do a quick look ahead at the
next token, but that's not a *huge* deal

=== Update

So I had initially abandoned the above because it appeared like it has too many edge cases, but reading
through what Docker themselves did, it does appear like they have a similar process:

https://github.com/moby/buildkit/blob/master/frontend/dockerfile/parser/parser.go#L297[Dockerfile Parser]

== Interesting note on `Dockerfiles` too

So, https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin[according to the docs],
the `docker` command actually supports piping data from `stdin` or other locations. That's an interesting idea: don't actually
*use* docker files, but rather generate them as needed from other things, and then run static analysis & what not on *those*.

Additionally, https://github.com/hadolint/language-docker/blob/master/src/Language/Docker/Parser/Instruction.hs#L41[Hadolint has some nice ideas as well]
